// Textos de las pantallas del comensal y del kiosco (español e inglés) y el texto de cada error de la caja.
// Hay una prueba que comprueba que cada clave existe en los dos idiomas y que cada código de error que puede
// devolver la caja tiene su texto.

export const IDIOMAS = ['es', 'en'];

export const T = {
  es: {
    mesaTitulo: 'Mesa {n}',
    ejemplo: 'restaurante de ejemplo',
    noEsTuMesa: '¿No es tu mesa? Avísale al mesero.',
    idiomaBoton: 'English',
    idiomaAria: 'Ver en inglés',
    llamarMesero: 'Llamar al mesero',
    pedirCuenta: 'Pedir la cuenta',
    verCuenta: 'Ver la cuenta',
    tabCarta: 'Carta',
    tabMesa: 'Mi mesa',
    tabCuenta: 'Cuenta',
    navCategorias: 'Categorías de la carta',
    preciosIncluyen: 'Precios con ITBMS incluido. No hay cargos adicionales.',
    preciosFonda: 'Precios finales, sin cargos adicionales. La comida y las bebidas sin alcohol no llevan ITBMS; las bebidas con alcohol incluyen el 10 %.',
    cartaDesfasada: 'La carta del local cambió y a este teléfono no le llegó completa: algún precio o plato puede no estar al día. El precio que vale es el que ves en «Mi mesa» después de enviar; si tienes dudas, pregúntale al mesero.',
    contiene: 'Contiene: {lista}',
    agotado: 'Agotado hoy',
    agregar: 'Agregar al pedido',
    agregarPrecio: 'Agregar al pedido · {precio}',
    agregado: '{cant} × {plato}: agregado a tu pedido',
    cantidad: 'Cantidad',
    menos: 'Quitar uno',
    mas: 'Agregar uno',
    nota: 'Nota para la cocina (opcional)',
    notaAyuda: 'Por ejemplo: sin hielo, bien cocido. No escribas datos personales.',
    eligeUna: 'Elige una',
    opcional: 'Opcional',
    faltaElegir: 'Elige «{grupo}» para seguir.',
    cerrar: 'Cerrar',
    verPedido: 'Ver pedido',
    platos1: '{n} plato',
    platosN: '{n} platos',
    tuPedido: 'Tu pedido · mesa {n}',
    carritoVacio: 'Todavía no agregaste nada. Toca un plato de la carta para agregarlo.',
    enviarCocina: 'Enviar a cocina',
    enviarMesero: 'Enviar al mesero',
    agotadoQuitalo: 'Se agotó: quítalo para enviar el pedido.',
    agotadoNoEnvia: 'Quita los platos agotados para poder enviar.',
    agotadoPlato: 'Se agotó «{plato}» mientras pedías. Toca «Ver pedido», quítalo y vuelve a enviar.',
    aprobacionNota: 'Primero lo ve el mesero y él lo pasa a la cocina.',
    sinAprobacionNota: 'Pasa directo a la cocina.',
    quitar: 'Quitar',
    editarCantidad: 'Cantidad de {plato}',
    enviando: 'Enviando…',
    pedidoEnviadoAviso: 'Pedido enviado. Síguelo en «Mi mesa».',
    sinRespuesta: 'Todavía no llega al local. Seguimos intentando; si tarda, avísale al mesero.',
    'pedido.por-aceptar': 'Esperando al mesero',
    'pedido.enviado': 'Enviado a cocina',
    'pedido.recibido': 'Recibido en cocina',
    'pedido.en-preparacion': 'En preparación',
    'pedido.listo': 'Listo, ya te lo llevan',
    'pedido.servido': 'Servido',
    'pedido.rechazado': 'No aceptado',
    'pedido.enviando': 'Enviando…',
    pasos: 'Avance del pedido',
    rechazadoMotivo: 'El mesero no lo aceptó: {motivo}',
    rechazadoSinMotivo: 'El mesero no lo aceptó. Pregúntale en persona.',
    ronda: 'Ronda {n}',
    desdeEste: 'desde este teléfono',
    desdeOtro: 'desde otro teléfono de la mesa',
    desdeMesero: 'tomado por el mesero',
    mesaVacia: 'Aún no hay pedidos en esta mesa. Pide desde la carta o con el mesero.',
    avisosTitulo: 'Avisos al mesero',
    tituloLlamar: '¿Para qué llamas al mesero?',
    'motivo.pedir': 'Pedir algo más',
    'motivo.ayuda': 'Necesito ayuda',
    'motivo.otra': 'Otra cosa',
    detalleOpcional: 'Detalle (opcional)',
    'aviso.mesero': 'Llamaste al mesero',
    'aviso.cuenta': 'Pediste la cuenta',
    'aviso.enviando': 'Enviando…',
    'aviso.abierta': 'Enviado: llegó al salón',
    'aviso.atendida': 'Visto por el mesero',
    'aviso.cancelada': 'Cancelado',
    yaNoHaceFalta: 'Ya no hace falta',
    tituloCuenta: 'Cuenta · mesa {n}',
    precuenta: 'Esta es una precuenta. La factura la emite el restaurante.',
    total: 'Total',
    incluyeItbms: 'Incluye ITBMS',
    itbmsTasa: 'ITBMS {tasa} % de {base}',
    itbmsCero: 'Sin ITBMS: {base}',
    cartaDigitalDe: 'Carta digital de',
    sinItbms: 'Sin ITBMS en la comida (fonda)',
    cuentaVacia: 'La cuenta está vacía: todavía no hay pedidos aceptados.',
    comoPagan: '¿Cómo pagan?',
    todoJunto: 'Todo junto',
    iguales: 'Partes iguales',
    porPlatos: 'Cada quien sus platos',
    entreCuantas: 'Entre cuántas personas',
    personas: '{n} personas',
    dividir: 'Dividir la cuenta',
    persona: 'Persona {n}',
    asignaAyuda: 'Marca de quién es cada plato. Si un plato es compartido, márcalo en varias personas y se reparte entre ellas.',
    faltanAsignar1: 'Falta 1 plato por asignar.',
    faltanAsignarN: 'Faltan {n} platos por asignar.',
    parteDe: 'Parte {n} de {total}',
    'parte.libre': 'Por pagar',
    'parte.pendiente': 'Pago por confirmar',
    'parte.pagada': 'Pagada',
    elegirParte: '¿Qué parte pagas?',
    cambiarDivision: 'Cambiar la división',
    divisionBloqueada: 'Ya hay un pago con esta división; para cambiarla, pídeselo al mesero.',
    divisionDesfasada: 'Se agregaron platos después de dividir. Vuelve a dividir la cuenta.',
    tuParte: 'Tu parte',
    loQueFalta: 'Lo que falta por pagar',
    pagarTodo: 'Pagar toda la cuenta',
    tituloPropina: 'Propina (voluntaria)',
    propinaSobre: 'Se calcula sobre {base}: lo consumido, con ITBMS.',
    pctBoton: '{pct} %',
    pctDetalle: '{pct} % de {base} = {monto}',
    otraCifra: 'Otra cifra',
    sinPropina: 'Sin propina',
    montoPropina: 'Monto de la propina en B/.',
    propinaElige: 'Elige una propina o «Sin propina» para seguir.',
    'propina.monto-ilegible': 'Escribe el monto con números, por ejemplo 3.50.',
    'propina.monto-negativo': 'La propina no puede ser negativa.',
    'propina.monto-alto': 'La propina no puede pasar de lo consumido. Si quieres dejar más, díselo al mesero.',
    tituloMetodo: '¿Cómo pagas?',
    'metodo.yappy': 'Yappy',
    'metodo.tarjeta': 'Tarjeta',
    'metodo.mesero': 'Pagar al mesero',
    'metodo.efectivo': 'Efectivo',
    yappyExplica: 'Abre Yappy, escanea este QR del local y escribe el monto exacto: {monto}.',
    yappyEjemplo: 'QR de ejemplo. En un local real aquí va su QR de Yappy Comercial.',
    tarjetaExplica: 'En un local real te lleva a su enlace de pago con tarjeta. En esta demo no se cobra nada.',
    meseroExplica: 'Le avisamos al mesero que pagas en la mesa, en efectivo o con tarjeta.',
    consumo: 'Consumo',
    propina: 'Propina',
    totalPagar: 'Total a pagar',
    simularPago: 'Simular pago (demo)',
    avisarPagoMesero: 'Avisar al mesero que pago aquí',
    eligeMetodo: 'Elige cómo pagas para seguir.',
    comprobante: 'Comprobante',
    pagoSimulado: 'Pago simulado: en esta demo no se movió dinero.',
    pagoAlMesero: 'Pagas al mesero en la mesa.',
    'pago.pendiente': 'Pendiente de confirmar: la caja lo marca cuando recibe el dinero.',
    'pago.confirmado': 'Pagado: la caja confirmó el pago.',
    'pago.rechazado': 'La caja no encontró este pago. Habla con el mesero.',
    'pago.enviando': 'Enviando el aviso de pago…',
    mesaPagada: 'La mesa está pagada. ¡Gracias por venir!',
    resenaInvita: '¿Te gustó? Una reseña en Google le ayuda al local.',
    dejarResena: 'Dejar una reseña en Google',
    resenaDemo: 'En el local real, este enlace abre su ficha de Google. Aquí no lleva a ningún lado.',
    privacidad: 'Privacidad',
    privacidadTitulo: 'Aviso de privacidad',
    privacidadTexto: 'Para ver la carta, pedir o pagar no te pedimos nombre, teléfono ni correo. Este teléfono guarda tu pedido en curso y el idioma elegido, nada más. Lo que pides llega al restaurante con el número de mesa. Si escribes algo en una nota, lo lee la cocina: no pongas datos personales. Panamá protege los datos personales con la Ley 81 de 2019; el responsable es el restaurante.',
    avisoRelevo: 'Modo demostración entre dispositivos: los datos pasan por un servidor público de pruebas (ntfy.sh). No escribas datos reales.',
    'conexion.local': 'En este dispositivo',
    'conexion.conectando': 'Conectando con el local…',
    'conexion.conectado': 'Conectado con el local',
    'conexion.sin-conexion': 'Sin conexión; reintentando en {s} s',
    noResponde: 'La pantalla del local no responde. Puedes ver la carta; para pedir, llama al mesero en persona.',
    queMesa: '¿En qué mesa estás?',
    escaneaOEscribe: 'Escanea el QR de tu mesa o escribe el número que está en la placa.',
    numeroMesa: 'Número de mesa',
    abrirMesa: 'Abrir la carta de mi mesa',
    numeroInvalido: 'Escribe el número que ves en la placa, de 1 a 999.',
    numeroAyuda: 'Es el número grande de la placa de la mesa.',
    enTuPedido: '{n} en tu pedido',
    sinSala: 'Este enlace no trae el código del local. Escanea el QR de la placa de tu mesa.',
    mesaNoExiste: 'La mesa {n} no existe en este local. Revisa el número de la placa o avísale al mesero.',
    pinTitulo: 'PIN de la mesa',
    pinAyuda: 'Son los 3 números impresos en la placa de tu mesa.',
    pinContinuar: 'Enviar con este PIN',
    pinFormato: 'El PIN son 3 números.',
    pinNoCoincide: 'Ese PIN no coincide con el de la placa. Revisa los 3 números y vuelve a enviar.',
    entendido: 'Entendido',
    cuentaCerrada: 'Tu cuenta quedó cerrada. ¡Gracias por venir!',
    nuevaCuenta: 'Pedir otra vez en esta mesa',
    cargandoCarta: 'Cargando la carta…',
    cartaError: 'No se pudo cargar la carta. Revisa la señal y vuelve a intentar.',
    reintentar: 'Volver a intentar',
    vacioCategoria: 'No hay platos en esta categoría.',
    cuentaPagadaTotal: 'Pagado',
    faltaPagar: 'Falta por pagar',
    pagosPendientes: 'Por confirmar',
    // kiosco
    tocaParaPedir: 'Toca para pedir',
    kioscoEjemplo: 'Pixbae · restaurante de ejemplo',
    paraComerAqui: 'Para comer aquí',
    paraLlevar: 'Para llevar',
    dondeComes: '¿Dónde lo vas a comer?',
    comoPagasKiosco: '¿Cómo pagas?',
    pagarCaja: 'Pagar en caja',
    pagarTarjeta: 'Pagar con tarjeta',
    tarjetaKiosco: 'En el local real pagas en el lector de tarjetas de esta pantalla. En la demo se simula.',
    tuOrden: 'Tu número de orden',
    pasaCaja: 'Pasa a la caja a pagar. Te llamamos por este número.',
    pagadoKiosco: 'Pago simulado. Te llamamos por este número cuando esté listo.',
    sigues: '¿Sigues ahí?',
    volvemos: 'Volvemos al inicio en {s} s y se borra el pedido.',
    volvemosOrden: 'Esta pantalla vuelve al inicio en {s} s.',
    sigoAqui: 'Sigo aquí',
    sugerencia: '¿Le agregas {plato}?',
    agregarSugerencia: 'Agregar {precio}',
    noGracias: 'No, gracias',
    empezarDeNuevo: 'Empezar de nuevo',
    nuevoPedido: 'Nuevo pedido',
    irAPagar: 'Ir a pagar',
    tuPedidoKiosco: 'Tu pedido',
    kioscoVacio: 'Toca un plato para agregarlo aquí.',
    volver: 'Volver',
    confirmarPedido: 'Confirmar pedido',
    enviarPedidoKiosco: 'Enviar a cocina',
  },
  en: {
    mesaTitulo: 'Table {n}',
    ejemplo: 'sample restaurant',
    noEsTuMesa: 'Not your table? Let your server know.',
    idiomaBoton: 'Español',
    idiomaAria: 'Ver en español',
    llamarMesero: 'Call your server',
    pedirCuenta: 'Ask for the bill',
    verCuenta: 'See the bill',
    tabCarta: 'Menu',
    tabMesa: 'My table',
    tabCuenta: 'Bill',
    navCategorias: 'Menu sections',
    preciosIncluyen: 'Prices include ITBMS (sales tax). No extra charges.',
    preciosFonda: 'Final prices, no extra charges. Food and non-alcoholic drinks carry no ITBMS (sales tax); alcoholic drinks include the 10 %.',
    cartaDesfasada: "The restaurant changed its menu and this phone didn't get all of it: a price or dish may be out of date. The price that counts is the one under “My table” after you send; if in doubt, ask your server.",
    contiene: 'Contains: {lista}',
    agotado: 'Sold out today',
    agregar: 'Add to order',
    agregarPrecio: 'Add to order · {precio}',
    agregado: '{cant} × {plato}: added to your order',
    cantidad: 'Quantity',
    menos: 'One less',
    mas: 'One more',
    nota: 'Note for the kitchen (optional)',
    notaAyuda: "For example: no ice, well done. Please don't write personal details.",
    eligeUna: 'Choose one',
    opcional: 'Optional',
    faltaElegir: 'Choose “{grupo}” to continue.',
    cerrar: 'Close',
    verPedido: 'View order',
    platos1: '{n} item',
    platosN: '{n} items',
    tuPedido: 'Your order · table {n}',
    carritoVacio: 'Nothing here yet. Tap a dish on the menu to add it.',
    enviarCocina: 'Send to kitchen',
    enviarMesero: 'Send to your server',
    agotadoQuitalo: 'Sold out: remove it to send your order.',
    agotadoNoEnvia: 'Remove the sold-out dishes to send.',
    agotadoPlato: '“{plato}” sold out while you were ordering. Tap “View order”, remove it and send again.',
    aprobacionNota: 'Your server checks it first and passes it to the kitchen.',
    sinAprobacionNota: 'It goes straight to the kitchen.',
    quitar: 'Remove',
    editarCantidad: 'Quantity of {plato}',
    enviando: 'Sending…',
    pedidoEnviadoAviso: 'Order sent. Follow it under “My table”.',
    sinRespuesta: "It hasn't reached the restaurant yet. We keep trying; if it takes long, tell your server.",
    'pedido.por-aceptar': 'Waiting for your server',
    'pedido.enviado': 'Sent to the kitchen',
    'pedido.recibido': 'Received in the kitchen',
    'pedido.en-preparacion': 'Being prepared',
    'pedido.listo': 'Ready, on its way',
    'pedido.servido': 'Served',
    'pedido.rechazado': 'Not accepted',
    'pedido.enviando': 'Sending…',
    pasos: 'Order progress',
    rechazadoMotivo: 'Your server did not accept it: {motivo}',
    rechazadoSinMotivo: 'Your server did not accept it. Please ask in person.',
    ronda: 'Round {n}',
    desdeEste: 'from this phone',
    desdeOtro: 'from another phone at this table',
    desdeMesero: 'taken by your server',
    mesaVacia: 'No orders at this table yet. Order from the menu or with your server.',
    avisosTitulo: 'Requests to your server',
    tituloLlamar: 'Why are you calling your server?',
    'motivo.pedir': 'Order something else',
    'motivo.ayuda': 'I need help',
    'motivo.otra': 'Something else',
    detalleOpcional: 'Details (optional)',
    'aviso.mesero': 'You called your server',
    'aviso.cuenta': 'You asked for the bill',
    'aviso.enviando': 'Sending…',
    'aviso.abierta': 'Sent: the floor got it',
    'aviso.atendida': 'Seen by your server',
    'aviso.cancelada': 'Cancelled',
    yaNoHaceFalta: 'Never mind',
    tituloCuenta: 'Bill · table {n}',
    precuenta: 'This is a pre-bill. The restaurant issues the invoice.',
    total: 'Total',
    incluyeItbms: 'Includes ITBMS',
    itbmsTasa: 'ITBMS {tasa} % of {base}',
    itbmsCero: 'No ITBMS: {base}',
    cartaDigitalDe: 'Digital menu by',
    sinItbms: 'No ITBMS on food (fonda)',
    cuentaVacia: 'The bill is empty: no accepted orders yet.',
    comoPagan: 'How are you paying?',
    todoJunto: 'All together',
    iguales: 'Split evenly',
    porPlatos: 'Each pays their own',
    entreCuantas: 'How many people',
    personas: '{n} people',
    dividir: 'Split the bill',
    persona: 'Person {n}',
    asignaAyuda: 'Mark who had each dish. For a shared dish, mark several people and it is split between them.',
    faltanAsignar1: '1 dish is not assigned yet.',
    faltanAsignarN: '{n} dishes are not assigned yet.',
    parteDe: 'Share {n} of {total}',
    'parte.libre': 'Unpaid',
    'parte.pendiente': 'Payment to confirm',
    'parte.pagada': 'Paid',
    elegirParte: 'Which share are you paying?',
    cambiarDivision: 'Change the split',
    divisionBloqueada: 'Someone already paid with this split; ask your server to change it.',
    divisionDesfasada: 'Dishes were added after splitting. Split the bill again.',
    tuParte: 'Your share',
    loQueFalta: 'What is left to pay',
    pagarTodo: 'Pay the whole bill',
    tituloPropina: 'Tip (optional)',
    propinaSobre: 'Calculated on {base}: what you had, tax included.',
    pctBoton: '{pct} %',
    pctDetalle: '{pct} % of {base} = {monto}',
    otraCifra: 'Other amount',
    sinPropina: 'No tip',
    montoPropina: 'Tip amount in B/.',
    propinaElige: 'Choose a tip or “No tip” to continue.',
    'propina.monto-ilegible': 'Type the amount in numbers, for example 3.50.',
    'propina.monto-negativo': 'The tip cannot be negative.',
    'propina.monto-alto': 'The tip cannot be more than what you had. To leave more, tell your server.',
    tituloMetodo: 'How do you pay?',
    'metodo.yappy': 'Yappy',
    'metodo.tarjeta': 'Card',
    'metodo.mesero': 'Pay your server',
    'metodo.efectivo': 'Cash',
    yappyExplica: 'Open Yappy, scan this QR from the restaurant and type the exact amount: {monto}.',
    yappyEjemplo: "Sample QR. A real restaurant shows its Yappy Comercial QR here.",
    tarjetaExplica: "At a real restaurant this takes you to its card payment link. Nothing is charged in this demo.",
    meseroExplica: 'We let your server know you are paying at the table, cash or card.',
    consumo: 'Food and drinks',
    propina: 'Tip',
    totalPagar: 'Total to pay',
    simularPago: 'Simulate payment (demo)',
    avisarPagoMesero: "Tell my server I'm paying here",
    eligeMetodo: 'Choose how you pay to continue.',
    comprobante: 'Receipt',
    pagoSimulado: 'Simulated payment: no money moved in this demo.',
    pagoAlMesero: 'You pay your server at the table.',
    'pago.pendiente': 'Waiting for confirmation: the cashier marks it when the money arrives.',
    'pago.confirmado': 'Paid: the cashier confirmed it.',
    'pago.rechazado': 'The cashier could not find this payment. Please talk to your server.',
    'pago.enviando': 'Sending the payment notice…',
    mesaPagada: 'The table is paid. Thank you for coming!',
    resenaInvita: 'Enjoyed it? A Google review helps the restaurant.',
    dejarResena: 'Leave a Google review',
    resenaDemo: 'At a real restaurant this link opens its Google listing. Here it goes nowhere.',
    privacidad: 'Privacy',
    privacidadTitulo: 'Privacy notice',
    privacidadTexto: "To see the menu, order or pay we don't ask for your name, phone or email. This phone keeps your current order and your language, nothing else. Your order reaches the restaurant with the table number. Anything you write in a note is read by the kitchen: please don't add personal details. Panama protects personal data under Law 81 of 2019; the restaurant is responsible for it.",
    avisoRelevo: 'Cross-device demo mode: data goes through a public test server (ntfy.sh). Do not enter real data.',
    'conexion.local': 'On this device',
    'conexion.conectando': 'Connecting to the restaurant…',
    'conexion.conectado': 'Connected to the restaurant',
    'conexion.sin-conexion': 'Offline; retrying in {s} s',
    noResponde: "The restaurant's screen is not answering. You can browse the menu; to order, ask your server in person.",
    queMesa: 'Which table are you at?',
    escaneaOEscribe: 'Scan the QR on your table or type the number on the table sign.',
    numeroMesa: 'Table number',
    abrirMesa: 'Open the menu for my table',
    numeroInvalido: 'Type the number you see on the sign, from 1 to 999.',
    numeroAyuda: 'The large number on the table sign.',
    enTuPedido: '{n} in your order',
    sinSala: "This link doesn't include the restaurant code. Scan the QR on your table sign.",
    mesaNoExiste: "Table {n} doesn't exist here. Check the number on the sign or tell your server.",
    pinTitulo: 'Table PIN',
    pinAyuda: 'The 3 digits printed on your table sign.',
    pinContinuar: 'Send with this PIN',
    pinFormato: 'The PIN is 3 digits.',
    pinNoCoincide: "That PIN doesn't match the table sign. Check the 3 digits and send again.",
    entendido: 'Got it',
    cuentaCerrada: 'Your bill is closed. Thank you for coming!',
    nuevaCuenta: 'Order again at this table',
    cargandoCarta: 'Loading the menu…',
    cartaError: "The menu didn't load. Check your signal and try again.",
    reintentar: 'Try again',
    vacioCategoria: 'No dishes in this section.',
    cuentaPagadaTotal: 'Paid',
    faltaPagar: 'Left to pay',
    pagosPendientes: 'To confirm',
    tocaParaPedir: 'Tap to order',
    kioscoEjemplo: 'Pixbae · sample restaurant',
    paraComerAqui: 'Eat in',
    paraLlevar: 'Take away',
    dondeComes: 'Where will you eat?',
    comoPagasKiosco: 'How do you pay?',
    pagarCaja: 'Pay at the counter',
    pagarTarjeta: 'Pay by card',
    tarjetaKiosco: 'At a real restaurant you pay on this screen’s card reader. The demo simulates it.',
    tuOrden: 'Your order number',
    pasaCaja: "Please pay at the counter. We'll call this number.",
    pagadoKiosco: "Simulated payment. We'll call this number when it's ready.",
    sigues: 'Still there?',
    volvemos: 'Going back to the start in {s} s; your order will be cleared.',
    volvemosOrden: 'This screen goes back to the start in {s} s.',
    sigoAqui: "I'm still here",
    sugerencia: 'Add {plato}?',
    agregarSugerencia: 'Add {precio}',
    noGracias: 'No, thanks',
    empezarDeNuevo: 'Start over',
    nuevoPedido: 'New order',
    irAPagar: 'Go to payment',
    tuPedidoKiosco: 'Your order',
    kioscoVacio: 'Tap a dish to add it here.',
    volver: 'Back',
    confirmarPedido: 'Confirm order',
    enviarPedidoKiosco: 'Send to kitchen',
  },
};

/** Texto con variables `{x}`. Si falta en inglés, usa el español; si falta en los dos, devuelve la clave. */
export function t(idioma, clave, vars = {}) {
  const s = T[idioma]?.[clave] ?? T.es[clave] ?? clave;
  return s.replace(/\{(\w+)\}/g, (_, k) => (k in vars ? String(vars[k]) : `{${k}}`));
}

/** La línea sobre los precios según el tipo de local (en una fonda la comida va sin ITBMS). */
export function textoPrecios(idioma, tipoLocal) {
  return t(idioma, tipoLocal === 'fonda' ? 'preciosFonda' : 'preciosIncluyen');
}

/** Errores que pueden llegarle al comensal (es/en). */
export const ERRORES_COMENSAL = {
  es: {
    'mesa-inexistente': 'Esa mesa no existe en este local. Revisa el número de la placa.',
    pin: 'El PIN no coincide con el de la placa de tu mesa. Toca «Ver pedido» y escríbelo otra vez.',
    'pedido-vacio': 'El pedido está vacío.',
    'pedido-largo': 'El pedido tiene demasiados renglones; envíalo en dos partes.',
    'plato-inexistente': 'Uno de los platos ya no está en la carta. Revisa tu pedido.',
    agotado: 'Un plato se agotó mientras pedías. Toca «Ver pedido», quítalo y vuelve a enviar.',
    cantidad: 'La cantidad de un plato no es válida (de 1 a 20).',
    'faltan-modificadores': 'A un plato le falta elegir una opción, por ejemplo el acompañamiento.',
    modificadores: 'Una opción elegida ya no existe en la carta. Vuelve a elegirla.',
    demasiados: 'Ya hay 3 pedidos de esta mesa esperando al mesero. Espera a que los revise.',
    'cuenta-vacia': 'Todavía no hay nada que cobrar en esta mesa.',
    'division-bloqueada': 'Ya hay un pago con esta división; para cambiarla, pídeselo al mesero.',
    partes: 'Elige entre 1 y 20 personas.',
    'sin-asignar': 'Faltan platos por asignar a alguien.',
    tipo: 'Esa forma de dividir no existe.',
    accion: 'No se entendió la solicitud.',
    metodo: 'Elige cómo pagas.',
    monto: 'El monto no coincide con la cuenta. Vuelve a abrirla.',
    propina: 'La propina no es válida.',
    'sin-division': 'La cuenta ya no está dividida. Vuelve a elegir cómo pagan.',
    'division-desfasada': 'Se agregaron platos después de dividir. Vuelve a dividir la cuenta.',
    parte: 'Esa parte no existe.',
    'parte-tomada': 'Esa parte ya la pagó alguien más.',
    'monto-alto': 'El monto pasa de lo que falta por pagar.',
    aviso: 'Ese aviso ya no existe.',
    transicion: 'Eso ya cambió en el salón. Mira el estado actual.',
    rechazado: 'El mesero no aceptó el pedido. Pregúntale en persona.',
  },
  en: {
    'mesa-inexistente': "That table doesn't exist here. Check the number on the sign.",
    pin: "The PIN doesn't match the one on your table sign. Tap “View order” and type it again.",
    'pedido-vacio': 'The order is empty.',
    'pedido-largo': 'The order has too many lines; send it in two parts.',
    'plato-inexistente': 'One of the dishes is no longer on the menu. Check your order.',
    agotado: 'A dish sold out while you were ordering. Tap “View order”, remove it and send again.',
    cantidad: 'A quantity is not valid (1 to 20).',
    'faltan-modificadores': 'A dish is missing a choice, such as the side.',
    modificadores: 'A chosen option is no longer on the menu. Please choose again.',
    demasiados: 'There are already 3 orders from this table waiting for your server. Please wait for them to be checked.',
    'cuenta-vacia': 'There is nothing to pay at this table yet.',
    'division-bloqueada': 'Someone already paid with this split; ask your server to change it.',
    partes: 'Choose between 1 and 20 people.',
    'sin-asignar': 'Some dishes are not assigned to anyone.',
    tipo: "That way of splitting doesn't exist.",
    accion: 'The request was not understood.',
    metodo: 'Choose how you pay.',
    monto: "The amount doesn't match the bill. Please open it again.",
    propina: 'The tip is not valid.',
    'sin-division': 'The bill is no longer split. Choose how you pay again.',
    'division-desfasada': 'Dishes were added after splitting. Split the bill again.',
    parte: "That share doesn't exist.",
    'parte-tomada': 'Someone else already paid that share.',
    'monto-alto': 'The amount is more than what is left to pay.',
    aviso: 'That request no longer exists.',
    transicion: 'That already changed on the floor. See the current status.',
    rechazado: 'Your server did not accept the order. Please ask in person.',
  },
};

/** Errores del personal (solo español). */
export const ERRORES_PERSONAL = {
  pedido: 'No se encontró ese pedido.',
  pago: 'No se encontró ese pago.',
  pagos: 'Agrega al menos un pago (hasta 4).',
  recibido: 'El efectivo recibido no alcanza para el monto y la propina.',
  'saldo-pendiente': 'Falta cobrar {detalle}. Cobra la cuenta antes de liberar la mesa.',
  'pedidos-en-curso': 'Hay pedidos sin servir. Márcalos servidos antes de liberar la mesa.',
  'pagos-pendientes': 'Hay pagos por confirmar. Confírmalos o recházalos primero.',
  renglon: 'No se encontró ese renglón.',
  estacion: 'Esa estación no tiene renglones en este pedido.',
  'faltan-renglones': 'Faltan renglones por marcar en este ticket.',
  plano: 'El plano tiene errores: {detalle}',
  carta: 'La carta tiene errores: {detalle}',
  ajustes: '{detalle}',
  orden: 'No se encontró esa orden.',
  'accion-invalida': 'Acción no válida.',
  'tipo-desconocido': 'Acción desconocida.',
  'no-permitido': 'Esa acción solo se puede hacer desde el salón.',
  'mesa-invalida': 'Falta el número de mesa.',
};

export function textoError(codigo, idioma = 'es', detalle = null) {
  const s = ERRORES_COMENSAL[idioma]?.[codigo] ?? ERRORES_COMENSAL.es[codigo] ?? ERRORES_PERSONAL[codigo] ?? `Error: ${codigo}`;
  const d = Array.isArray(detalle) ? detalle.join(' ') : detalle ?? '';
  return s.replace('{detalle}', String(d));
}
